IHAM_app/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', form_test, name='form'),
    url(r'^add_data/', add_order_data_to_models, name='add_data'),
    url(r'^get_city/', get_city, name='get_city'),
    url(r'^get_price/(?P<destination>.*)/', get_price, name='get_price'),
    url(r'^index/', index, name='index'),
    url(r'^check_code/', check_code, name='check_code'),
    url(r'^orderlist/', OrderListToJSON, name='OrderListToJSON')
]

IHAMask/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import IHAM_app.urls as IHAM_app
import IHAM_loginAdmin.urls as IHAM_loginAdmin

from django.views.generic import RedirectView
from IHAM_app.views import index
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^form/', include(IHAM_app, namespace='IHAM_app')),
    url(r'^$',index, name='index'),
    url(r'^login/', include(IHAM_loginAdmin, namespace='IHAM_loginAdmin')),
]

IHAM_app/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class OrderList(models.Model):
    customerName = models.CharField(max_length=140, blank=False)
    customerEmail = models.EmailField(max_length=140, blank=False)
    customerPhone = models.CharField(max_length=140, blank=False)
    productQuantityA = models.IntegerField()
    productQuantityB = models.IntegerField()
    customerAddress = models.TextField(blank=False)
    productPrice = models.BigIntegerField() #Ini field baru zar
    shippingPrice = models.BigIntegerField() #Ini field baru zar
    grandTotalPrice = models.BigIntegerField(blank=False)
    promoCode = models.CharField(max_length=140, blank=True)
    paidFlage = models.BooleanField(default=False) #Ini field baru zar
    deliveredFlage = models.BooleanField(default=False) #Ini field baru zar
    created_on = models.DateTimeField(default=timezone.now)

class promoCode(models.Model):
	promoName = models.CharField(max_length=10, blank=False)
	promoAmount = models.FloatField(blank=False)

class upcomingEvents(models.Model):
	eventName= models.CharField(max_length=140, blank=False)
	eventURL= models.CharField(max_length=140, blank=False)
	eventDate= models.CharField(max_length=140, blank=False)
	eventVenue= models.CharField(max_length=140, blank=False)
	def __str__(self):
		return self.eventName

class FAQ(models.Model):
	titleIndo = models.TextField()
	titleEng = models.TextField()
	isiIndo = models.TextField()
	isiEng = models.TextField()
	def __str__(self):
		return self.titleEng

IHAM_app/views.py
from django.shortcuts import render
import http.client
import json
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from .models import upcomingEvents, FAQ, OrderList
from IHAM_loginAdmin.models import PromoCode
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
import ast
from django.conf import settings
from django.core.mail import send_mail, EmailMessage

# Create your views here.
response = {}

def form_test(request):
    return render(request, 'formTest.html', response)

def index(request):
    response['events'] = upcomingEvents.objects.all()
    response['faq'] = FAQ.objects.all()
    return render(request, 'index.html', response)

# Method untuk get data dari form order lalu masukkan ke models
@csrf_exempt
def add_order_data_to_models(request):
    if(request.method == 'POST'):
        customerName = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        customerEmail = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
        customerPhone = request.POST['phone'] if request.POST['phone'] != "" else "Anonymous"
        productQuantityA = request.POST['productQuantityA'] if request.POST['productQuantityA'] != "" else 0
        productQuantityB = request.POST['productQuantityB'] if request.POST['productQuantityB'] != "" else 0
        promoCode = request.POST['promoCode'] if request.POST['promoCode'] != '' else "no-code-submitted"
        productPrice = request.POST['productPrice'] if request.POST['productPrice'] != "" else 0
        shippingPrice = request.POST['shippingPrice'] if request.POST['shippingPrice'] != "Sorry JNE can't reach your city yet" else 0
        grandTotalPrice = request.POST['totalPrice'] if request.POST["totalPrice"] != "" else 0

        productQuantityA = int(productQuantityA)
        productQuantityB = int(productQuantityB)
        productPrice = int(productPrice)
        shippingPrice = int(shippingPrice)
        grandTotalPrice = int(grandTotalPrice)


        customerAddress = request.POST['street'] if request.POST['street'] != "" else "Anonymous"
        city = request.POST['kota'] if request.POST['kota'] != "" else "Anonymous"

        print("productQuantityA " + str(productQuantityA))
        print("productQuantityB " + str(productQuantityB))
        print("street " + str(customerAddress))
        print("city " + str(city))
        # print("productPriceA " + str(productPriceA))
        # print("productPriceB " + str(productPriceB))
        # print("totalProductPrice " + str(totalProductPrice))
        # print("productQuantityA " + str(productQuantityA))
        print("shippingPrice " + str(shippingPrice))

        order = OrderList(
            customerName = customerName,
            customerEmail = customerEmail,
            customerPhone = customerPhone,
            productQuantityA=productQuantityA,
            productQuantityB = productQuantityB,
            customerAddress = customerAddress,
            productPrice = productPrice,
            shippingPrice = shippingPrice,
            grandTotalPrice = grandTotalPrice,
            promoCode = promoCode
            )
        order.save()

        #JALANIN SEND EMAIL DISINI
        # email = EmailMessage('title', 'body', to=[email])
        # email.send()
        email_content='''<HTML>
                        <HEAD>
                            <META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=utf-8">
                            <TITLE></TITLE>
                            <META NAME="GENERATOR" CONTENT="LibreOffice 4.1.6.2 (Linux)">
                            <META NAME="CREATED" CONTENT="20180313;10500000000000">
                            <META NAME="CHANGEDBY" CONTENT="Favian Kharisma Hazman">
                            <META NAME="CHANGED" CONTENT="20180313;10600000000000">
                            <META NAME="AppVersion" CONTENT="16.0000">
                            <META NAME="DocSecurity" CONTENT="0">
                            <META NAME="HyperlinksChanged" CONTENT="false">
                            <META NAME="LinksUpToDate" CONTENT="false">
                            <META NAME="ScaleCrop" CONTENT="false">
                            <META NAME="ShareDoc" CONTENT="false">
                            <STYLE TYPE="text/css">
                            <!--
                                @page { size: 8.5in 11in; margin: 1in }
                                P { margin-bottom: 0.08in; direction: ltr; widows: 2; orphans: 2 }
                            -->
                            </STYLE>
                        </HEAD>
                        <BODY LANG="en-US" DIR="LTR">
                        <P ALIGN=JUSTIFY STYLE="margin-bottom: 0in">Halo <I>'''+customerName+'''</I> 
                        </P>
                        <P ALIGN=JUSTIFY STYLE="text-indent: 0.5in; margin-bottom: 0in">Terima
                        kasih karena telah membantu kami melestarikan alam dan mempercayakan
                        kulit cantikmu pada <B>IHA Mask</B>! Hanya dengan <B>Rp 89.000,00</B>
                        saja kamu bisa mendapatkan kulit sehat dan cerah dalam sekejap.
                        Jangan lupa segera lakukan pembayaran ke nomor rekening berikut:</P>
                        <P ALIGN=JUSTIFY STYLE="margin-bottom: 0in"><BR>
                        </P>
                        <P ALIGN=CENTER STYLE="margin-bottom: 0in"><B>8700175198</B></P>
                        <P ALIGN=CENTER STYLE="margin-bottom: 0in"><B>BCA</B></P>
                        <P ALIGN=CENTER STYLE="margin-bottom: 0in"><B>A/N Muhammad Fachry</B></P>
                        <P ALIGN=JUSTIFY STYLE="margin-bottom: 0in"><BR>
                        </P>
                        <P ALIGN=JUSTIFY STYLE="margin-bottom: 0in">    Jika sudah melakukan
                        pembayaran, segera kirimkan bukti transfer-mu dengan membalas e-mail
                        ini selambat-lambatnya empat hari setelah pemesanan agar pengiriman
                        dapat segera diproses. Sudah tidak sabar ‘kan untuk merawat kulit
                        cantikmu? <I>Happy shopping! </I>
                        </P>
                        <P ALIGN=CENTER STYLE="margin-bottom: 0in"><BR>
                        </P>
                        <P ALIGN=CENTER STYLE="margin-bottom: 0in"><BR>
                        </P>
                        <P ALIGN=RIGHT STYLE="margin-bottom: 0in"><I>Nature to get better,</I></P>
                        <P ALIGN=RIGHT STYLE="margin-bottom: 0in"><I>Have a nice day!</I></P>
                        <P ALIGN=RIGHT STYLE="margin-bottom: 0in"><BR>
                        </P>
                        </BODY>
                        </HTML>'''
        msg = EmailMessage("Terima Kasih Telah Memesan IHAMASK!", email_content, settings.EMAIL_HOST_USER, [customerEmail])
        msg.content_subtype = "html"
        msg.send()
        return HttpResponse("Complete")

#export data orderan to json
def OrderListToJSON(request):
    data = OrderList.objects.all()
    return HttpResponse(serializers.serialize('json', data), content_type="application/json")

# method untuk mendapatkan semua kota atau kabupaten
def get_city(request):

    conn = http.client.HTTPSConnection("api.rajaongkir.com")

    headers = { 'key': "ea827133edd06f4d89a5296c0661c3e4" }

    conn.request("GET", "/starter/city", headers=headers)
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    data_city = json.loads(data)
    # print(data)
    return JsonResponse(data_city)


def get_price(request, destination):

    conn = http.client.HTTPSConnection("api.rajaongkir.com")
    print("destination " + destination)
    payload = "origin=22&destination="+destination+"&weight=1000&courier=jne"

    headers = {
        'key': "ea827133edd06f4d89a5296c0661c3e4",
        'content-type': "application/x-www-form-urlencoded"
        }

    conn.request("POST", "/starter/cost", payload, headers)

    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    cost_Data = json.loads(data)
    return JsonResponse(cost_Data)

@csrf_exempt
def check_code(request):
    if(request.method == 'POST'):
        current_code = request.POST['code']
        email = request.POST['email_check']
        try:
            promo = PromoCode.objects.get(promoCode=current_code)
            promo = model_to_dict(promo)
            promo = ast.literal_eval(promo)
            if OrderList.objects.filter(customerEmail=email).exists():
                return HttpResponse("email")
            return JsonResponse(promo)
        except PromoCode.DoesNotExist:
            promo = None
            print(promo)
            return HttpResponse(promo)

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

IHAM_app/templates/formTest.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Form Test</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/formTest.css' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Select2 Script -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
      <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

</head>

<body style="display: none">
  <!-- <div data-theme="light" id="rajaongkir-widget"></div> -->
  <section name="form">
    <div>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1>Order</h1>
            <form id="form" method="POST" action="{% url 'IHAM_app:add_data' %}">
              {% csrf_token %}
              <div class="col-md-6" style="padding-left: 0;">
                <div class="form-group">
                  <div class="input-group">
                    <input type="text" class="form-control" id="InputName" placeholder="Your name" required pattern="[A-Za-z ]+" title="Name must be alphabet" name="name">
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">
                    <input type="email" class="form-control" id="InputEmail" placeholder="Enter email" required="required" name="email" onkeyup="email_checkPromo()">
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Enter phone number" required pattern="[0-9]{10,12}" id="phone-number" title="Input must be 10-12 'number'" name="phone">
                  </div>
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-check">
                    <p><Strong>Tea Tree Organic</Strong> Painless Peel Off Mask <span class="badge badge-secondary">IDR 89000</span></p>
                    <input type="number" class="form-control w-100" placeholder="Enter quantity(Number)" id="quantity-productA" pattern="[0-9]+" name="productQuantityA">
                  </div>
                </div>
                <div class="col-md-3" style="display: none">
                  <div class="form-check">
                     <label class="form-check-label">
                       <input class="form-check-input" type="checkbox" id="checkboxB">Product B (Rp 7000)&nbsp;
                     </label>
                     <input type="text" class="form-control w-100" placeholder="Enter quantity(Number)" id="quantity-productB" style="display: none" pattern="[0-9]+" name="productQuantityB">
                   </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <p>Total Product Price: Rp <span id="harga-barang">0</span></p>
                </div>
              </div>
              <br>
              <label class="form-control-label">Order Address:</label>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <input type="text" class="form-control w-100" required="required" name="street" onkeyup="updateAddress()" id="street" placeholder="Enter your address">
                  </div>
                  <div class="form-group">
                    <select class="form-control my-select-city" name="city" style="width: 100%;">
                      <option value=""></option>
                    </select>
                  </div>
                  <div class="form-group">
                    <input type="text" class="form-control w-100" required pattern="[0-9]{5}" name="postal" onkeyup="updateAddress()" id="postal" placeholder="Enter your postal code" title="Postal code consist of 5 number">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <p>Ship To <span id="order-address"></span></p>
                  <p>Shipping Price: Rp <span id="ongkos-kirim">0</span></p>
                  <div class="form-group">
                    <div class="row">
                      <div class="col-md-6">
                        <input type="text" class="form-control w-100" name="promotion-code" id="promotion-code" placeholder="Input if you have promotion code" onkeyup="check_promo()">
                      </div>
                      <div class="col-md-6">
                        <span id="promo-icon"></span>
                      </div>
                    </div>
                  </div>
                  <h2>Total Price: Rp <span id="total-harga">0</span></h2>
                </div>
              </div>
              <br>
              <button type="submit" class="btn d-flex" id='submit-button'>Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>

<!-- Jquery n Bootstrap Script -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
<!-- Select2 -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
<!-- JS -->
<script src="{% static 'js/formTest.js' %}"></script>
</html>